apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.deployment.containers.uccms.port }}
    targetPort: {{ .Values.deployment.containers.uccms.port }}
  selector:
    app: {{ .Values.service.name }}
