apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.serviceName.svc }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "dish_smsf.name" . }}
    helm.sh/chart: {{ include "dish_smsf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: usmsf
  template:
    metadata:
      labels:
        app: usmsf
        version: v1
    spec:
      {{- if .Values.global.nodeName }}
      nodeName: {{ .Values.global.nodeName }}
      {{- end }}
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: {{ .Values.deployment.volumes.config.name }}
        configMap:
          name: {{ .Values.configmap.name }}
      - name: log-volume
        emptyDir: {}
      - name: tcpdump 
        emptyDir: {}
      - name: {{ .Values.deployment.volumes.secret.accessTokenCheck.name }}
        configMap:
          name: {{ .Values.secret.name.accessTokenChecker }}
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.global.timezone }}

      hostAliases:
        {{- range $aliasIdx, $alias := .Values.deployment.hostAliases }}
        - ip: {{ $alias.ip | quote }}
          hostnames:
          {{- range $hostnameIdx, $hostname := $alias.hostnames }}
          - {{ $hostname | quote }}
          {{- end }}
        {{- end }}
    
      containers:
      - name: usmsf
        image: {{ .Values.deployment.containers.usmsf.image }}
        imagePullPolicy: {{ .Values.deployment.containers.usmsf.imagePullPolicy }}
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: {{ .Values.deployment.volumes.config.name }}
          mountPath: /app/config
        - name: {{ .Values.deployment.volumes.sharedData.name }}
          mountPath: /tmp
        - name: {{ .Values.deployment.volumes.log.name }}
          mountPath: /app/logs
        - name: {{ .Values.deployment.volumes.secret.accessTokenCheck.name }}
          mountPath: /app/config/access_token_checker
        - name: tz-config
          mountPath: /etc/localtime
        ports:
        - containerPort: {{ .Values.global.smsf.serverPort.forNFServer.http }}
        - containerPort: {{ .Values.global.smsf.serverPort.forNFServer.https }}
        - containerPort: {{ .Values.global.smsf.serverPort.forInternal.http }}
        - containerPort: {{ .Values.global.smsf.serverPort.forConfigMgr.http }}
        env:
        - name: USMSF_HOME
          value: /app
        - name: USMSF_CONFIG_FILE
          value: /app/config/usmsf.conf
        - name: SUBSMGR_CONFIG_FILE
          value: /app/config/usmsf.conf
        - name: USMSF_FAILNOTI_ADDR
          value: http://{{ .Values.global.smsf.ipaddr.expose.svc.ipv4 }}:{{ .Values.global.smsf.serverPort.forNFServer.http }}
        - name: USMSF_FQDN
          value: {{ .Values.global.serviceName.svc }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}
        - name: DIA_POD_HOST
          value: {{ .Values.global.serviceName.dia }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}:{{ .Values.global.port.dia.container }}
        - name: SMS_STAT_DIR
          value: /tmp/stat
        - name: TRACE_HOME_ENV_NAME
          value: /tmp/trace
        - name: CONF_POD_HOST
          value: {{ .Values.global.serviceName.uccms }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}:{{ .Values.global.port.uccms.servicePort }}
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        {{- if eq .Values.deployment.containers.usmsf.useManualStart "true" }}
        command: ["sh", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        {{- end }}
      - name: redis-server
        image: {{ .Values.deployment.containers.redisServer.image }}
        imagePullPolicy: {{ .Values.deployment.containers.redisServer.imagePullPolicy }}
        ports:
         - containerPort: {{ .Values.deployment.containers.redisServer.containerPort }}
      - name: emsubagt
        image: {{ .Values.deployment.containers.emsubagt.image }}
        imagePullPolicy: {{ .Values.deployment.containers.emsubagt.imagePullPolicy }}
        volumeMounts:
        - name: shared-data 
          mountPath: /tmp
        env:
        - name: EM_SERVICE
          value: {{ .Values.global.serviceName.emagt }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}
        - name: MY_SERVICE
          value: WEB_SERVICE
        - name: EM_HTTP_PORT
          value: {{ .Values.global.port.emagt.http | quote }}
        - name: EM_WS_PORT
          value: {{ .Values.global.port.emagt.ws | quote }}
        - name: MY_GROUP
          value: WEB_SERVICE
        - name: MYSQL_ADDR
          value: "{{ .Values.global.serviceName.mariadb }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}"
        - name: ENALBED_TRACE
          value: "true"
        - name: MMCD
          value: "false"
