# Default values for dish-smsf-dia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 2000m
    memory: 2048Mi

nodeSelector: {}

tolerations: []

affinity: {}

deployment:
  containers:
    diaSvc:
      image: "camel.uangel.com:5000/dia_svc:v060"
      #image: "camel.uangel.com:5000/dia_svc:latest"
      imagePullPolicy: "IfNotPresent"
    adif:
      #image: "camel.uangel.com:5000/adif:v050"
      image: "camel.uangel.com:5000/adif:latest"
      imagePullPolicy: "IfNotPresent"

configmaps:
  names:
    adif: "usmsf-adif-conf"
    if: "usmsf-if-conf"
  adifConf:
    sections:
      adif:
        activeStandby: "false"
      udifWorker:
        threadCount: 4
  udiaConfXml:
    useIp6: "no"
  httpifLogger:
    logLevels:
      root: "DEBUG"
      com_uangel: "DEBUG"

